version: "3"
services: 
  dreamer:
    image: dreamer-deploy:latest
    build: 
      context: ../../
      dockerfile: $PWD/Dockerfile.deploy
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTH}
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    stdin_open: true
    tty: true
    runtime: nvidia
    command: tail -f