version: "3"
services: 
  dreamer:
    image: dreamer:latest
    build: 
      context: ../../
      dockerfile: $PWD/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTH}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix:rw
      - ${XAUTH}:${XAUTH}
      - "$PWD/../:/app/:rw" 
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    stdin_open: true
    tty: true